require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'Dating' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'RNAudioRecord', :path => '../node_modules/react-native-audio-record'
  pod 'RNSoundPlayer', :path => '../node_modules/react-native-sound-player'
  
  permissions_path = '../node_modules/react-native-permissions/ios'
       pod 'Permission-Camera', :path => "#{permissions_path}/Camera/Permission-Camera.podspec"
       pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary/Permission-MediaLibrary.podspec"
       pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary/Permission-PhotoLibrary.podspec"
       pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways/Permission-LocationAlways.podspec"
       pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse/Permission-LocationWhenInUse.podspec"
       pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone/Permission-Microphone.podspec"

  target 'DatingTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
